<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20231105222735 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial database schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE account (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, number VARCHAR(64) NOT NULL, caption VARCHAR(255) NOT NULL, clabe VARCHAR(32) NOT NULL, username VARCHAR(32) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX UNIQ_7D3656A44A468FDE (clabe), INDEX IDX_7D3656A49033212A (tenant_id), INDEX IDX_7D3656A4DE12AB56 (created_by), INDEX IDX_7D3656A416FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE address (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, calle VARCHAR(255) NOT NULL, no_exterior VARCHAR(255) NOT NULL, no_interior VARCHAR(32) NOT NULL, colonia VARCHAR(255) NOT NULL, localidad VARCHAR(255) DEFAULT NULL, municipio VARCHAR(255) NOT NULL, estado VARCHAR(255) NOT NULL, pais VARCHAR(255) NOT NULL, cp VARCHAR(16) NOT NULL, identifier VARCHAR(255) DEFAULT NULL, checksum VARCHAR(64) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_D4E6F819395C3F3 (customer_id), INDEX IDX_D4E6F81DE12AB56 (created_by), INDEX IDX_D4E6F8116FE72E1 (updated_by), UNIQUE INDEX UNIQ_D4E6F81772E836A9395C3F3 (identifier, customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE clone_invoice (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, tenant_id INT DEFAULT NULL, default_address_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, rfc VARCHAR(13) NOT NULL, name VARCHAR(255) NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_81398E099033212A (tenant_id), UNIQUE INDEX UNIQ_81398E09BD94FB16 (default_address_id), INDEX IDX_81398E09DE12AB56 (created_by), INDEX IDX_81398E0916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, financial_month_id INT DEFAULT NULL, transaction_id INT DEFAULT NULL, invoice_id INT DEFAULT NULL, property_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, parent_id INT DEFAULT NULL, account_id INT DEFAULT NULL, type VARCHAR(32) NOT NULL, sequence_no SMALLINT DEFAULT NULL, filename VARCHAR(255) NOT NULL, is_consolidated TINYINT(1) NOT NULL, amount INT DEFAULT NULL, checksum VARCHAR(64) DEFAULT NULL, specs JSON DEFAULT NULL, issue_date DATETIME DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, discr VARCHAR(20) NOT NULL, is_legacy TINYINT(1) DEFAULT NULL, display_filename VARCHAR(255) DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, INDEX IDX_D8698A769033212A (tenant_id), INDEX IDX_D8698A76A739F6E0 (financial_month_id), INDEX IDX_D8698A762FC0CB0F (transaction_id), INDEX IDX_D8698A762989F1FD (invoice_id), INDEX IDX_D8698A76549213EC (property_id), INDEX IDX_D8698A76DE12AB56 (created_by), INDEX IDX_D8698A7616FE72E1 (updated_by), INDEX IDX_D8698A76727ACA70 (parent_id), INDEX IDX_D8698A769B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edoc (id INT AUTO_INCREMENT NOT NULL, tenant_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, type VARCHAR(32) NOT NULL, format VARCHAR(4) NOT NULL, filename VARCHAR(255) NOT NULL, checksum VARCHAR(64) DEFAULT NULL, issue_date DATETIME DEFAULT NULL, owner_id INT DEFAULT NULL, owner_type VARCHAR(255) DEFAULT NULL, owner_key VARCHAR(64) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_54BCFC5B9033212A (tenant_id), INDEX IDX_54BCFC5BDE12AB56 (created_by), INDEX IDX_54BCFC5B16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(191) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE financial_month (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, statement_id INT DEFAULT NULL, account_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, year SMALLINT NOT NULL, month SMALLINT NOT NULL, status VARCHAR(16) NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_FFD7FA299033212A (tenant_id), UNIQUE INDEX UNIQ_FFD7FA29849CB65B (statement_id), INDEX IDX_FFD7FA299B6B5FBA (account_id), INDEX IDX_FFD7FA29DE12AB56 (created_by), INDEX IDX_FFD7FA2916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, customer_id INT DEFAULT NULL, property_id INT DEFAULT NULL, substitutes_invoice_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, series VARCHAR(16) NOT NULL, number INT NOT NULL, recipient_rfc VARCHAR(13) NOT NULL, recipient_name VARCHAR(255) NOT NULL, currency VARCHAR(3) NOT NULL, amount INT NOT NULL, issue_date DATETIME NOT NULL, status VARCHAR(16) NOT NULL, data JSON DEFAULT NULL, url_pdf VARCHAR(1024) DEFAULT NULL, url_xml VARCHAR(1024) DEFAULT NULL, description VARCHAR(1024) DEFAULT NULL, year SMALLINT DEFAULT NULL, month SMALLINT DEFAULT NULL, is_complete TINYINT(1) NOT NULL, live_mode TINYINT(1) DEFAULT NULL, checksum_pdf VARCHAR(64) DEFAULT NULL, checksum_xml VARCHAR(64) DEFAULT NULL, cancellation_reason VARCHAR(255) DEFAULT NULL, cancellation_date DATETIME DEFAULT NULL, cancellation_data JSON DEFAULT NULL, payment_date DATETIME DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX UNIQ_906517445BCB0B1E (url_pdf), UNIQUE INDEX UNIQ_9065174464CF08F1 (url_xml), INDEX IDX_906517449033212A (tenant_id), INDEX IDX_906517449395C3F3 (customer_id), INDEX IDX_90651744549213EC (property_id), UNIQUE INDEX UNIQ_906517449D5A0651 (substitutes_invoice_id), INDEX IDX_90651744DE12AB56 (created_by), INDEX IDX_9065174416FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_schedule (id INT AUTO_INCREMENT NOT NULL, property_id INT NOT NULL, customer_id INT NOT NULL, tenant_id INT DEFAULT NULL, series_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, frequency VARCHAR(16) NOT NULL, scheduled_date DATE NOT NULL, next_issue_date DATE NOT NULL, is_active TINYINT(1) NOT NULL, concept VARCHAR(1024) NOT NULL, amount INT NOT NULL, tax_category VARCHAR(32) NOT NULL, monthly_payment_day INT DEFAULT NULL, invoice_template LONGTEXT DEFAULT NULL, payment_form VARCHAR(32) DEFAULT \'99\' NOT NULL, payment_method VARCHAR(32) DEFAULT \'PPD\' NOT NULL, invoice_usage VARCHAR(32) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_45104BA3549213EC (property_id), INDEX IDX_45104BA39395C3F3 (customer_id), INDEX IDX_45104BA39033212A (tenant_id), INDEX IDX_45104BA35278319C (series_id), INDEX IDX_45104BA3DE12AB56 (created_by), INDEX IDX_45104BA316FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice_task (id INT AUTO_INCREMENT NOT NULL, invoice_schedule_id INT NOT NULL, property_id INT NOT NULL, invoice_id INT DEFAULT NULL, customer_id INT NOT NULL, tenant_id INT DEFAULT NULL, series_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, first_date DATE NOT NULL, concept VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL, last_executed DATETIME DEFAULT NULL, year INT NOT NULL, month INT NOT NULL, live_mode TINYINT(1) DEFAULT NULL, invoice_template LONGTEXT DEFAULT NULL, amount INT NOT NULL, tax_category VARCHAR(32) NOT NULL, payment_form VARCHAR(32) NOT NULL, payment_method VARCHAR(32) NOT NULL, request_data JSON DEFAULT NULL, invoice_usage VARCHAR(32) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_50BBB940B345A0E6 (invoice_schedule_id), INDEX IDX_50BBB940549213EC (property_id), UNIQUE INDEX UNIQ_50BBB9402989F1FD (invoice_id), INDEX IDX_50BBB9409395C3F3 (customer_id), INDEX IDX_50BBB9409033212A (tenant_id), INDEX IDX_50BBB9405278319C (series_id), INDEX IDX_50BBB940DE12AB56 (created_by), INDEX IDX_50BBB94016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE property (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, caption VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, cadastral_number VARCHAR(32) DEFAULT NULL, is_active TINYINT(1) NOT NULL, slug VARCHAR(16) NOT NULL, match_string VARCHAR(255) NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX UNIQ_8BF21CDE989D9B62 (slug), INDEX IDX_8BF21CDE9033212A (tenant_id), INDEX IDX_8BF21CDEDE12AB56 (created_by), INDEX IDX_8BF21CDE16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE series (id INT AUTO_INCREMENT NOT NULL, tenant_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, code VARCHAR(4) NOT NULL, description VARCHAR(255) NOT NULL, source VARCHAR(3) DEFAULT NULL, is_active TINYINT(1) DEFAULT 0 NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_3A10012D9033212A (tenant_id), INDEX IDX_3A10012DDE12AB56 (created_by), INDEX IDX_3A10012D16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE statement (id INT AUTO_INCREMENT NOT NULL, tenant_id INT NOT NULL, account_id INT NOT NULL, document_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, starting_balance INT NOT NULL, ending_balance INT NOT NULL, year INT NOT NULL, month INT NOT NULL, no_deposits INT NOT NULL, no_withdrawals INT NOT NULL, account_number VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_C0DB51769033212A (tenant_id), INDEX IDX_C0DB51769B6B5FBA (account_id), UNIQUE INDEX UNIQ_C0DB5176C33F7837 (document_id), INDEX IDX_C0DB5176DE12AB56 (created_by), INDEX IDX_C0DB517616FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tenant (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, rfc VARCHAR(13) NOT NULL, name VARCHAR(255) NOT NULL, api_key VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, icon VARCHAR(32) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_4E59C462DE12AB56 (created_by), INDEX IDX_4E59C46216FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, statement_id INT NOT NULL, customer_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, amount INT NOT NULL, type VARCHAR(32) DEFAULT NULL, booking_date DATE NOT NULL, value_date DATE NOT NULL, sequence_no SMALLINT DEFAULT NULL, description VARCHAR(1024) NOT NULL, is_consolidated TINYINT(1) NOT NULL, status VARCHAR(16) NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_723705D1849CB65B (statement_id), INDEX IDX_723705D19395C3F3 (customer_id), INDEX IDX_723705D1DE12AB56 (created_by), INDEX IDX_723705D116FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), INDEX IDX_8D93D649DE12AB56 (created_by), INDEX IDX_8D93D64916FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle (id INT AUTO_INCREMENT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, uid VARCHAR(64) NOT NULL, owner VARCHAR(255) NOT NULL, license_plate VARCHAR(16) NOT NULL, make VARCHAR(32) NOT NULL, model VARCHAR(32) NOT NULL, year INT NOT NULL, color VARCHAR(32) NOT NULL, vin VARCHAR(255) DEFAULT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_1B80E486DE12AB56 (created_by), INDEX IDX_1B80E48616FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_insurance (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT NOT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, provider VARCHAR(255) NOT NULL, policy_number VARCHAR(64) NOT NULL, start_date DATE NOT NULL, expiry_date DATE NOT NULL, agent VARCHAR(255) DEFAULT NULL, amount INT NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_93B1EA1E545317D1 (vehicle_id), INDEX IDX_93B1EA1EDE12AB56 (created_by), INDEX IDX_93B1EA1E16FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_tax (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, payment_date DATE NOT NULL, amount INT NOT NULL, next_due_date DATE NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX IDX_14D563B0545317D1 (vehicle_id), INDEX IDX_14D563B0DE12AB56 (created_by), INDEX IDX_14D563B016FE72E1 (updated_by), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A416FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F819395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F8116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E099033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09BD94FB16 FOREIGN KEY (default_address_id) REFERENCES address (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E0916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A769033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76A739F6E0 FOREIGN KEY (financial_month_id) REFERENCES financial_month (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A762FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A762989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76549213EC FOREIGN KEY (property_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7616FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76727ACA70 FOREIGN KEY (parent_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A769B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE edoc ADD CONSTRAINT FK_54BCFC5B9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE edoc ADD CONSTRAINT FK_54BCFC5BDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE edoc ADD CONSTRAINT FK_54BCFC5B16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE financial_month ADD CONSTRAINT FK_FFD7FA299033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE financial_month ADD CONSTRAINT FK_FFD7FA29849CB65B FOREIGN KEY (statement_id) REFERENCES statement (id)');
        $this->addSql('ALTER TABLE financial_month ADD CONSTRAINT FK_FFD7FA299B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE financial_month ADD CONSTRAINT FK_FFD7FA29DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE financial_month ADD CONSTRAINT FK_FFD7FA2916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744549213EC FOREIGN KEY (property_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449D5A0651 FOREIGN KEY (substitutes_invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_90651744DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174416FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA3549213EC FOREIGN KEY (property_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA39395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA39033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA35278319C FOREIGN KEY (series_id) REFERENCES series (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA3DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_schedule ADD CONSTRAINT FK_45104BA316FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB940B345A0E6 FOREIGN KEY (invoice_schedule_id) REFERENCES invoice_schedule (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB940549213EC FOREIGN KEY (property_id) REFERENCES property (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB9402989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB9409395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB9409033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB9405278319C FOREIGN KEY (series_id) REFERENCES series (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB940DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_task ADD CONSTRAINT FK_50BBB94016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDEDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE property ADD CONSTRAINT FK_8BF21CDE16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE series ADD CONSTRAINT FK_3A10012D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE series ADD CONSTRAINT FK_3A10012DDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE series ADD CONSTRAINT FK_3A10012D16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE statement ADD CONSTRAINT FK_C0DB51769033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id)');
        $this->addSql('ALTER TABLE statement ADD CONSTRAINT FK_C0DB51769B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id)');
        $this->addSql('ALTER TABLE statement ADD CONSTRAINT FK_C0DB5176C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE statement ADD CONSTRAINT FK_C0DB5176DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE statement ADD CONSTRAINT FK_C0DB517616FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tenant ADD CONSTRAINT FK_4E59C462DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tenant ADD CONSTRAINT FK_4E59C46216FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1849CB65B FOREIGN KEY (statement_id) REFERENCES statement (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D19395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D116FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64916FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E48616FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle_insurance ADD CONSTRAINT FK_93B1EA1E545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_insurance ADD CONSTRAINT FK_93B1EA1EDE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle_insurance ADD CONSTRAINT FK_93B1EA1E16FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle_tax ADD CONSTRAINT FK_14D563B0545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_tax ADD CONSTRAINT FK_14D563B0DE12AB56 FOREIGN KEY (created_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE vehicle_tax ADD CONSTRAINT FK_14D563B016FE72E1 FOREIGN KEY (updated_by) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A49033212A');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A4DE12AB56');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A416FE72E1');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F819395C3F3');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F81DE12AB56');
        $this->addSql('ALTER TABLE address DROP FOREIGN KEY FK_D4E6F8116FE72E1');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E099033212A');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09BD94FB16');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E09DE12AB56');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY FK_81398E0916FE72E1');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A769033212A');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76A739F6E0');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A762FC0CB0F');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A762989F1FD');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76549213EC');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76DE12AB56');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A7616FE72E1');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76727ACA70');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A769B6B5FBA');
        $this->addSql('ALTER TABLE edoc DROP FOREIGN KEY FK_54BCFC5B9033212A');
        $this->addSql('ALTER TABLE edoc DROP FOREIGN KEY FK_54BCFC5BDE12AB56');
        $this->addSql('ALTER TABLE edoc DROP FOREIGN KEY FK_54BCFC5B16FE72E1');
        $this->addSql('ALTER TABLE financial_month DROP FOREIGN KEY FK_FFD7FA299033212A');
        $this->addSql('ALTER TABLE financial_month DROP FOREIGN KEY FK_FFD7FA29849CB65B');
        $this->addSql('ALTER TABLE financial_month DROP FOREIGN KEY FK_FFD7FA299B6B5FBA');
        $this->addSql('ALTER TABLE financial_month DROP FOREIGN KEY FK_FFD7FA29DE12AB56');
        $this->addSql('ALTER TABLE financial_month DROP FOREIGN KEY FK_FFD7FA2916FE72E1');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517449033212A');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517449395C3F3');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744549213EC');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_906517449D5A0651');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_90651744DE12AB56');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY FK_9065174416FE72E1');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA3549213EC');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA39395C3F3');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA39033212A');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA35278319C');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA3DE12AB56');
        $this->addSql('ALTER TABLE invoice_schedule DROP FOREIGN KEY FK_45104BA316FE72E1');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB940B345A0E6');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB940549213EC');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB9402989F1FD');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB9409395C3F3');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB9409033212A');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB9405278319C');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB940DE12AB56');
        $this->addSql('ALTER TABLE invoice_task DROP FOREIGN KEY FK_50BBB94016FE72E1');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDE9033212A');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDEDE12AB56');
        $this->addSql('ALTER TABLE property DROP FOREIGN KEY FK_8BF21CDE16FE72E1');
        $this->addSql('ALTER TABLE series DROP FOREIGN KEY FK_3A10012D9033212A');
        $this->addSql('ALTER TABLE series DROP FOREIGN KEY FK_3A10012DDE12AB56');
        $this->addSql('ALTER TABLE series DROP FOREIGN KEY FK_3A10012D16FE72E1');
        $this->addSql('ALTER TABLE statement DROP FOREIGN KEY FK_C0DB51769033212A');
        $this->addSql('ALTER TABLE statement DROP FOREIGN KEY FK_C0DB51769B6B5FBA');
        $this->addSql('ALTER TABLE statement DROP FOREIGN KEY FK_C0DB5176C33F7837');
        $this->addSql('ALTER TABLE statement DROP FOREIGN KEY FK_C0DB5176DE12AB56');
        $this->addSql('ALTER TABLE statement DROP FOREIGN KEY FK_C0DB517616FE72E1');
        $this->addSql('ALTER TABLE tenant DROP FOREIGN KEY FK_4E59C462DE12AB56');
        $this->addSql('ALTER TABLE tenant DROP FOREIGN KEY FK_4E59C46216FE72E1');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1849CB65B');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D19395C3F3');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1DE12AB56');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D116FE72E1');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649DE12AB56');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64916FE72E1');
        $this->addSql('ALTER TABLE vehicle DROP FOREIGN KEY FK_1B80E486DE12AB56');
        $this->addSql('ALTER TABLE vehicle DROP FOREIGN KEY FK_1B80E48616FE72E1');
        $this->addSql('ALTER TABLE vehicle_insurance DROP FOREIGN KEY FK_93B1EA1E545317D1');
        $this->addSql('ALTER TABLE vehicle_insurance DROP FOREIGN KEY FK_93B1EA1EDE12AB56');
        $this->addSql('ALTER TABLE vehicle_insurance DROP FOREIGN KEY FK_93B1EA1E16FE72E1');
        $this->addSql('ALTER TABLE vehicle_tax DROP FOREIGN KEY FK_14D563B0545317D1');
        $this->addSql('ALTER TABLE vehicle_tax DROP FOREIGN KEY FK_14D563B0DE12AB56');
        $this->addSql('ALTER TABLE vehicle_tax DROP FOREIGN KEY FK_14D563B016FE72E1');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE clone_invoice');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE edoc');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE financial_month');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_schedule');
        $this->addSql('DROP TABLE invoice_task');
        $this->addSql('DROP TABLE property');
        $this->addSql('DROP TABLE series');
        $this->addSql('DROP TABLE statement');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE vehicle_insurance');
        $this->addSql('DROP TABLE vehicle_tax');
    }
}
